branches:
  except:
    - pending

image: Visual Studio 2017

clone_folder: C:\projects\repo\feeds
cache:
  - '%LOCALAPPDATA%\0install.net'
  - '%APPDATA%\0install.net'
build_script:
  # Enable pushing back to GitHub
  - git config --global credential.helper store
  - ps: Add-Content ~\.git-credentials "https://${env:GITHUB_ACCESS_TOKEN}:x-oauth-basic@github.com`n"
  # Run watch scripts and push result to branch "pending"  
  - git checkout -b pending
  - ps: .\watch.ps1
  - git push origin pending --force
